### ISSUE TITLE
Spanish version

### ISSUE THREAD

**Issue by pataquets** [petergtz/alexa-wikipedia#112]
Browsed past issues, but neither #4 nor #14 provided any info.
What's needed to publish a Spanish version?
I can provide localized strings. Looks easy if the only files involved are those in `locale` dir. However, I can't run/test the skill without some (or a lot) of guidance, due to the invoved deployment (I've found no docs).
With that said, would it be possible to have a Spanish version, provided the strings are there?

**Comment by petergtz** [comment]
Hey @pataquets, sorry for the late response, I somehow missed this.

Yes, it should be doable. It's been quite a while since I've last deployed this (and unfortunately I don't have a GitHub action for this yet), and I think the Alexa CLI to deploy this completely changed, but there are no blockers in general, and I'd be happy to push a Spanish version.

There's a few more places though than just the `locale` dir. It also requires changes in:
- https://github.com/petergtz/alexa-wikipedia/tree/master/models
- https://github.com/petergtz/alexa-wikipedia/blob/master/skill.json

If you translate it, I'm happy to merge and deploy it :-).

**Comment by pataquets** [comment]
@petergtz Sent PR #114.

**Comment by pataquets** [comment]
Closed as completed. Thanks for sharing this skill and your help and support, @petergtz.
Maybe it's just my cluelessness with ASK, but I would like to suggest making testing & deployment steps more visible or (better yet) automated to allow easier collaboration by third parties. #12 would be great, as pipelines are like "live documentation" (dropped some info there).
