### ISSUE TITLE
Fix your MyGPT Skill! 🙏🏻😭 Also, less cheesecake... 

### ISSUE THREAD

**Issue by richaardvark** [petergtz/alexa-wikipedia#115]
Hello, sorry for reaching out to you directly. I didn't have Twitter before and I hate Twitter but I made one just to reach out to you. Please please please for the love of god fix your MyGPT Alexa skill! 🙏🏻🙏🏻😭 I've tried to reach out so many ways to you about this and have left feedback but the feedback doesn't even work in the app because of a frustrating error which has been happening ever since your last skill update. Maybe you've done this on purpose because you don't want to maintain the skill or there's some conflict because you work for AWS or something, who knows, but this skill was perfect at first. However, about 2 weeks ago the skill began refusing to provide a response to pretty much every other inquiry and instead gives a snotty comment that it refuses to answer because it may be against Amazon Alexa policy or some dumb crap. First of all, the skill needs to be marked mature anyway, just like all the other GPT skills, because even with whatever weird content filter you have attempted to enable it is still possible for GPT to return super adult-oriented responses. And that's the main issue - your profanity or whatever it is filter is absolutely broken and is total garbage. You cannot even ask the most basic, benign questions without it freaking out. Please please please fix this ! 🙏🏻🥺 It used to work beautifully but now it is driving me absolutely crazy. I really like your skill and depend upon it. 

https://youtu.be/LNTtyAKDPUQ

I also use My Encyclopedia regularly and it is great but the cheesecake thing is really old and annoying at this point... lol 😬🤷🏻‍♂️

**Comment by petergtz** [comment]
Hey, I really appreciate all your effort to reach me, and also apologize for not being able to respond earlier through other means. Unfortunately, there's no  way to respond to user reviews on Amazon.com. I've also gotten your in-skill feedback, read it and I understand everything you say. In fact, I planned to implement a feature to respond to user feedback on a user by user basis. However, and now this where the big thing drops: on April 13, Amazon has blocked MyGPT skill for new users due to policy violations towards profanity, explicit content, hate speech etc. And it threatened to block it for all users if I don't fix the issues. Since I don't know which answers exactly they define as violation, I had to err on filtering too much than too little to get out of "probation period". To this day though, I haven't been able to comply. And the only reason it's not blocked entirely, is because I have gotten extensions, because they couldn't give me concrete examples yet. So I'm discussions with Amazon advocates, but I'm still waiting for that. Once I'm green again, I'm happy to make that filter smarter and less strict, and hopefully work better for you. Right now it's indeed a pretty dumb filter on specific words. But until I know there's actually a future for this skill, I'm not planning to spend time on improving it. This is a hobby project for me. Defining the skill as mature does not happen through the developer, but through Amazon during certification. I cannot influence that. I hope you understand. And again, apologies for ruining your experience, but I'm operating in a platform that I cannot control and where I don't define policies.

**Comment by petergtz** [comment]
Hey @richaardvark, I was able to get my skill re-certified, which took a lot of effort as you can guess from the time it took to get this through. I removed the filters for now. Let's see how long this will work.  It should work nicely again. Would really appreciate if you could adjust your review on amazon.com. Of course, I can't give any guarantees if I won't run into any trouble in the future 😬. We'll see.

**Comment by richaardvark** [comment]
It's wonderful and works so well!!! :) 😍🙌🏻🎉  Thank you so so very much for taking time to do this and for sticking it out through the frustrations that were making things difficult. I have updated my review to 5 stars and gave a nice, positive review.  Thank you again!  Also, I like the beeping so much more than the "ummm... ummm..."     The only other suggestion I would have is to change the **_"I can tell you more about this... shall I?"_** prompt to the slightly shorter but just as clear **_"Shall I tell you more about this?"_** just because it saves a tiny amount of time when interacting with Alexa but other than that I have only positive things to say now. I don't know how you are able to offer this service at no cost 😮🙊

**Comment by petergtz** [comment]
Hey @richaardvark, I've created a pseudo git repo for issues: https://github.com/petergtz/Alexa-MyGPT-Skill

I'm going to drop your feedbacks there too, and will also respond. I think that's a better channel for communication. Feel free to give feedback through Alexa. But the GH issues will allow me to respond easily.
